version: "3"  # optional since v1.27.0
services:
  webserver_alice:
    build: .
    environment:
      - exposePort=55501
    ports:
      - "55501:55501"
    network_mode: "host"
  webserver_bob:
    build: .
    environment:
      - exposePort=55502
    ports:
      - "55502:55502"
    network_mode: "host"
  webserver_charlie:
    build: .
    environment:
      - exposePort=55503
    ports:
      - "55503:55503"
    network_mode: "host"